name: 'pull request merge'

on:
  pull_request:
    types: [labeled]

jobs:
  pull_request_merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ startsWith(github.event.label.name, 'merge-ff') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fast Forword Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: ${{ github.event.pull_request.head.ref }}
        development_branch: ${{ github.event.pull_request.base.ref }}
        allow_ff: true
        allow_forks: false
        ff_only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
